project_name: kwh_prediction
io:
  engine: duckdb
  duckdb_path: C:\Users\Asus\PycharmProjects\NEDCO_data_viz_app\data\warehouse.duckdb
  table: prod.sales
  sql: null
data:
  id_col: meterid
  date_col: chargedate
  month_col: month
  target_col: kwh
  location_col: loc
  residence_col: res
  currency_cols:
  - ghc
  - paymoney
  expected_frequency: M
time:
  unreliable_after: '2020-09-30'
  tz: UTC
paths:
  data_raw: C:\Users\Asus\PycharmProjects\NEDCO_data_viz_app\notebooks\kwh_prediction\data\raw
  data_clean: C:\Users\Asus\PycharmProjects\NEDCO_data_viz_app\notebooks\kwh_prediction\data\clean
  data_feature: C:\Users\Asus\PycharmProjects\NEDCO_data_viz_app\notebooks\kwh_prediction\data\feature
  models: C:\Users\Asus\PycharmProjects\NEDCO_data_viz_app\notebooks\kwh_prediction\models
  inference: C:\Users\Asus\PycharmProjects\NEDCO_data_viz_app\notebooks\kwh_prediction\inference
  reports: C:\Users\Asus\PycharmProjects\NEDCO_data_viz_app\notebooks\kwh_prediction\reports
  logs: C:\Users\Asus\PycharmProjects\NEDCO_data_viz_app\notebooks\kwh_prediction\logs
  config_dir: C:\Users\Asus\PycharmProjects\NEDCO_data_viz_app\notebooks\kwh_prediction\config
  src: C:\Users\Asus\PycharmProjects\NEDCO_data_viz_app\notebooks\kwh_prediction\src
random_seed: 42
evaluation_metrics:
- rmse
- mae
- mape
- r2
